"""Ordinal -> exported-name tables for the Win16 system modules.

Source of truth: the Wine project's 16-bit spec files (krnl386.exe16.spec,
user.exe16.spec, gdi.exe16.spec, sound.drv16.spec, win87em.dll16.spec),
fetched 2026-07-07.  Only ordinals that a target executable has actually
imported are listed; extend from the same source as new games need more.
"""
from __future__ import annotations

ORDINAL_NAMES: dict[str, dict[int, str]] = {
    "KERNEL": {
        1: "FatalExit",
        3: "GetVersion",
        5: "LocalAlloc",
        6: "LocalReAlloc",
        7: "LocalFree",
        10: "LocalSize",
        16: "GlobalReAlloc",
        20: "GlobalSize",
        23: "LockSegment",
        24: "UnlockSegment",
        30: "WaitEvent",
        49: "GetModuleFileName",
        51: "MakeProcInstance",
        52: "FreeProcInstance",
        74: "OpenFile",
        91: "InitTask",
        102: "DOS3Call",
        127: "GetPrivateProfileInt",
        128: "GetPrivateProfileString",
        129: "WritePrivateProfileString",
        131: "GetDOSEnvironment",
        137: "FatalAppExit",
        178: "__WINFLAGS",          # equate: absolute constant, not code
    },
    "USER": {
        1: "MessageBox",
        5: "InitApp",
        6: "PostQuitMessage",
        10: "SetTimer",
        12: "KillTimer",
        18: "SetCapture",
        19: "ReleaseCapture",
        22: "SetFocus",
        28: "ClientToScreen",
        31: "IsIconic",
        32: "GetWindowRect",
        33: "GetClientRect",
        34: "EnableWindow",
        39: "BeginPaint",
        40: "EndPaint",
        41: "CreateWindow",
        42: "ShowWindow",
        53: "DestroyWindow",
        56: "MoveWindow",
        57: "RegisterClass",
        62: "SetScrollPos",
        64: "SetScrollRange",
        66: "GetDC",
        68: "ReleaseDC",
        69: "SetCursor",
        79: "IntersectRect",
        87: "DialogBox",
        88: "EndDialog",
        91: "GetDlgItem",
        92: "SetDlgItemText",
        93: "GetDlgItemText",
        94: "SetDlgItemInt",
        95: "GetDlgItemInt",
        101: "SendDlgItemMessage",
        107: "DefWindowProc",
        108: "GetMessage",
        110: "PostMessage",
        113: "TranslateMessage",
        114: "DispatchMessage",
        125: "InvalidateRect",
        154: "CheckMenuItem",
        155: "EnableMenuItem",
        157: "GetMenu",
        160: "DrawMenuBar",
        171: "WinHelp",
        173: "LoadCursor",
        174: "LoadIcon",
        175: "LoadBitmap",
        176: "LoadString",
        177: "LoadAccelerators",
        178: "TranslateAccelerator",
        179: "GetSystemMetrics",
        194: "DlgDirSelectComboBox",
        195: "DlgDirListComboBox",
        250: "GetMenuState",
        403: "UnregisterClass",
        404: "GetClassInfo",
        414: "ModifyMenu",
        420: "wsprintf",
    },
    "GDI": {
        2: "SetBkMode",
        7: "SetStretchBltMode",
        9: "SetTextColor",
        29: "PatBlt",
        33: "TextOut",
        34: "BitBlt",
        35: "StretchBlt",
        45: "SelectObject",
        51: "CreateCompatibleBitmap",
        52: "CreateCompatibleDC",
        66: "CreateSolidBrush",
        68: "DeleteDC",
        69: "DeleteObject",
        87: "GetStockObject",
        93: "GetTextMetrics",
    },
    "SOUND": {
        1: "OpenSound",
        2: "CloseSound",
        3: "SetVoiceQueueSize",
        4: "SetVoiceNote",
        5: "SetVoiceAccent",
        9: "StartSound",
        10: "StopSound",
    },
    "WIN87EM": {
        1: "__fpMath",
    },
}


def api_name(module: str, ordinal: int) -> str:
    """Human name for MODULE.ordinal, e.g. 'USER.108:GetMessage'."""
    name = ORDINAL_NAMES.get(module.upper(), {}).get(ordinal)
    return f"{module.upper()}.{ordinal}" + (f":{name}" if name else "")
