"""Ordinal -> exported-name tables for the Win16 system modules.

Source of truth: the Wine project's 16-bit spec files (krnl386.exe16.spec,
user.exe16.spec, gdi.exe16.spec, sound.drv16.spec, win87em.dll16.spec),
fetched 2026-07-07.  Only ordinals that a target executable has actually
imported are listed; extend from the same source as new games need more.
"""
from __future__ import annotations

ORDINAL_NAMES: dict[str, dict[int, str]] = {
    "KERNEL": {
        1: "FatalExit",
        3: "GetVersion",
        57: "GetProfileInt",
        58: "GetProfileString",
        59: "WriteProfileString",
        135: "GetSystemDirectory",
        5: "LocalAlloc",
        6: "LocalReAlloc",
        7: "LocalFree",
        10: "LocalSize",
        15: "GlobalAlloc",
        16: "GlobalReAlloc",
        17: "GlobalFree",
        18: "GlobalLock",
        19: "GlobalUnlock",
        20: "GlobalSize",
        23: "LockSegment",
        24: "UnlockSegment",
        30: "WaitEvent",
        49: "GetModuleFileName",
        51: "MakeProcInstance",
        52: "FreeProcInstance",
        60: "FindResource",
        61: "LoadResource",
        62: "LockResource",
        63: "FreeResource",
        74: "OpenFile",
        81: "_lclose",
        82: "_lread",
        83: "_lcreat",
        84: "_llseek",
        85: "_lopen",
        86: "_lwrite",
        88: "lstrcpy",
        91: "InitTask",
        102: "DOS3Call",
        113: "__AHSHIFT",           # equate: absolute constant (3)
        114: "__AHINCR",            # equate: absolute constant (8)
        127: "GetPrivateProfileInt",
        128: "GetPrivateProfileString",
        129: "WritePrivateProfileString",
        131: "GetDOSEnvironment",
        132: "GetWinFlags",
        134: "GetWindowsDirectory",
        137: "FatalAppExit",
        178: "__WINFLAGS",          # equate: absolute constant, not code
    },
    "USER": {
        1: "MessageBox",
        5: "InitApp",
        28: "ClientToScreen",
        29: "ScreenToClient",
        30: "WindowFromPoint",
        104: "MessageBeep",
        272: "IsZoomed",
        45: "BringWindowToTop",
        49: "IsWindowVisible",
        82: "InvertRect",
        106: "GetKeyState",
        109: "PeekMessage",
        186: "SwapMouseButton",
        236: "GetCapture",
        229: "GetTopWindow",
        230: "GetNextWindow",
        262: "GetWindow",
        232: "SetWindowPos",
        237: "GetUpdateRgn",
        37: "SetWindowText",
        61: "ScrollWindow",
        126: "InvalidateRgn",
        128: "ValidateRgn",
        129: "GetClassWord",
        130: "SetClassWord",
        244: "EqualRect",
        6: "PostQuitMessage",
        10: "SetTimer",
        12: "KillTimer",
        13: "GetTickCount",
        17: "GetCursorPos",
        18: "SetCapture",
        19: "ReleaseCapture",
        22: "SetFocus",
        28: "ClientToScreen",
        31: "IsIconic",
        32: "GetWindowRect",
        33: "GetClientRect",
        34: "EnableWindow",
        39: "BeginPaint",
        40: "EndPaint",
        24: "RemoveProp",
        25: "GetProp",
        26: "SetProp",
        41: "CreateWindow",
        42: "ShowWindow",
        50: "FindWindow",
        53: "DestroyWindow",
        81: "FillRect",
        124: "UpdateWindow",
        151: "CreateMenu",
        152: "DestroyMenu",
        156: "GetSystemMenu",
        159: "GetSubMenu",
        263: "GetMenuItemCount",
        412: "RemoveMenu",
        413: "DeleteMenu",
        158: "SetMenu",
        410: "InsertMenu",
        411: "AppendMenu",
        56: "MoveWindow",
        57: "RegisterClass",
        62: "SetScrollPos",
        63: "GetScrollPos",
        64: "SetScrollRange",
        65: "GetScrollRange",
        66: "GetDC",
        68: "ReleaseDC",
        69: "SetCursor",
        72: "SetRect",
        79: "IntersectRect",
        85: "DrawText",
        87: "DialogBox",
        88: "EndDialog",
        91: "GetDlgItem",
        92: "SetDlgItemText",
        93: "GetDlgItemText",
        94: "SetDlgItemInt",
        95: "GetDlgItemInt",
        101: "SendDlgItemMessage",
        107: "DefWindowProc",
        108: "GetMessage",
        110: "PostMessage",
        111: "SendMessage",
        113: "TranslateMessage",
        114: "DispatchMessage",
        125: "InvalidateRect",
        154: "CheckMenuItem",
        155: "EnableMenuItem",
        157: "GetMenu",
        160: "DrawMenuBar",
        171: "WinHelp",
        173: "LoadCursor",
        174: "LoadIcon",
        175: "LoadBitmap",
        176: "LoadString",
        177: "LoadAccelerators",
        178: "TranslateAccelerator",
        179: "GetSystemMetrics",
        194: "DlgDirSelectComboBox",
        195: "DlgDirListComboBox",
        249: "GetAsyncKeyState",
        250: "GetMenuState",
        282: "SelectPalette",
        283: "RealizePalette",
        286: "GetDesktopWindow",
        403: "UnregisterClass",
        404: "GetClassInfo",
        414: "ModifyMenu",
        420: "wsprintf",
    },
    "GDI": {
        1: "SetBkColor",
        2: "SetBkMode",
        61: "CreatePen",
        3: "SetMapMode",
        22: "IntersectClipRect",
        30: "SaveDC",
        39: "RestoreDC",
        64: "CreateRectRgn",
        134: "GetRgnBox",
        181: "RectInRegion",
        7: "SetStretchBltMode",
        9: "SetTextColor",
        29: "PatBlt",
        33: "TextOut",
        34: "BitBlt",
        35: "StretchBlt",
        38: "Escape",
        45: "SelectObject",
        51: "CreateCompatibleBitmap",
        52: "CreateCompatibleDC",
        56: "CreateFont",
        66: "CreateSolidBrush",
        68: "DeleteDC",
        69: "DeleteObject",
        80: "GetDeviceCaps",
        87: "GetStockObject",
        91: "GetTextExtent",
        93: "GetTextMetrics",
        119: "AddFontResource",
        150: "UnrealizeObject",
        345: "GetTextAlign",
        346: "SetTextAlign",
        349: "SetMapperFlags",
        360: "CreatePalette",
        363: "GetPaletteEntries",
        370: "GetNearestPaletteIndex",
        374: "GetSystemPaletteUse",
        375: "GetSystemPaletteEntries",
        443: "SetDIBitsToDevice",
    },
    "SOUND": {
        1: "OpenSound",
        2: "CloseSound",
        3: "SetVoiceQueueSize",
        4: "SetVoiceNote",
        5: "SetVoiceAccent",
        9: "StartSound",
        10: "StopSound",
    },
    "WIN87EM": {
        1: "__fpMath",
    },
    "MMSYSTEM": {
        2: "sndPlaySound",
    },
}


def api_name(module: str, ordinal: int) -> str:
    """Human name for MODULE.ordinal, e.g. 'USER.108:GetMessage'."""
    name = ORDINAL_NAMES.get(module.upper(), {}).get(ordinal)
    return f"{module.upper()}.{ordinal}" + (f":{name}" if name else "")
