"""Recovery-IR generation for a loaded Win16 (NE) machine.

The Win16 front-end over the generic irgen core
(``dos_re.lift.irgen_core`` — per-entry scan, record serialization,
fail-loud unsupported ledger, deterministic JSON).  This module supplies the
Win16 triple:

* **fetch** — code bytes through the loaded image's selector map
  (``mem.sel_base``), so a paragraph-based CS resolves exactly as the
  interpreter resolves it;
* **probe** — a FRESH scratch clone per entry via ``win16.verify
  .clone_machine``.  Probing executes instructions and execution mutates the
  scratch (stack pushes, memory writes) — a probe shared across entries steps
  later instructions against corrupted state and reports false
  decoder-mismatches;
* **effect tagger** — the Win16 platform effect is a far transfer into the
  import-thunk segment (``loader.THUNK_SEG``), tagged ``api:<name>`` from
  ``cpu.hook_names`` (the same classification ``win16.callgraph`` applies to
  raw call sites; here it runs on the decoder's ``far_target``).  Everything
  else falls through to the DOS tagger — a Win16 C runtime genuinely does raw
  INT 21h I/O.

Addressing convention: callers pass entries as **NE pairs** ``(ne_seg, off)``
(1-based segment index), the human-facing convention of symbol tables and
reports.  ALL IR records are keyed by **paragraph-base** ``CS:IP`` — the
convention the lift/link/install pipeline speaks — with the NE identity
(``ne_seg`` + any caller-supplied symbol metadata) embedded per record via the
core's identity provider.  Addresses are the canonical keys; names are
naming evidence.

This layer never learns a game: entries, symbol metadata and fact lists come
from the consuming game-port project.
"""
from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping

from dos_re.lift.irgen_core import (  # noqa: F401  (re-exported for runners)
    IR_VERSION, build_document, dos_effect_tag, dump_document, write_document)

from .loader import THUNK_SEG

_NOTICE = ("AUTOGENERATED by win16.irgen -- DO NOT HAND EDIT. Regenerate "
           "from the original binary, entries, recovery facts, and the "
           "current win16_re/dos_re toolchain (dos_re docs/recovery_ir.md).")

NEPair = tuple[int, int]


def make_effect_tagger(machine) -> Callable[[Any], str | None]:
    """Tag far transfers into the import-thunk segment as ``api:<name>``;
    everything else classifies under the DOS tagger (raw INT 21h paths)."""
    hook_names = machine.cpu.hook_names

    def tag(inst) -> str | None:
        ft = inst.far_target
        if ft is not None and ft[0] == THUNK_SEG:
            # call_far or jmp_far (a tail-called thunk is the same API effect).
            return hook_names.get((THUNK_SEG, ft[1]), f"api:slot_{ft[1]:04X}")
        return dos_effect_tag(inst)

    return tag


def _fetch_for(machine, cs: int) -> Callable[[int], int]:
    lin = machine.mem.sel_base.get(cs & 0xFFFC, cs * 16)
    data = machine.mem.data
    return lambda ip: data[lin + (ip & 0xFFFF)]


def _probe_for(machine, machine_factory, cs: int):
    """A fresh scratch interpreter per entry (see module docstring)."""
    from .verify import clone_machine
    scratch = clone_machine(machine, machine_factory)
    cpu = scratch.cpu
    cpu.replacement_hooks.clear()
    cpu.hook_names.clear()
    cpu.hook_verifier = None
    cpu.trace_enabled = False

    def probe(ip: int):
        ip &= 0xFFFF
        cpu.s.cs, cpu.s.ip = cs & 0xFFFF, ip
        try:
            cpu.step()
        except Exception:  # noqa: BLE001 — an unprobeable address is a datum
            return None
        return ((cpu.s.ip - ip) & 0xFFFF) or None

    return probe


def _git_head(path: Path) -> str:
    try:
        return subprocess.run(["git", "-C", str(path), "rev-parse", "HEAD"],
                              capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:  # noqa: BLE001
        return "unknown"


def toolchain_provenance() -> str:
    """win16_re + dos_re commit hashes (no timestamps — determinism)."""
    import dos_re as _dos_re
    win16_root = Path(__file__).resolve().parents[1]
    dos_root = Path(_dos_re.__file__).resolve().parents[1]
    return (f"win16_re={_git_head(win16_root)} "
            f"dos_re={_git_head(dos_root)}")


def build_ir(machine, entries: Iterable[NEPair], *,
             machine_factory: Callable[[], Any] | None = None,
             keep_interpreted: Iterable[NEPair] = (),
             boundary_heads: Iterable[NEPair] = (),
             dispatch_entries: Iterable[NEPair] = (),
             names: Mapping[NEPair, Mapping[str, Any]] | None = None,
             exe: str | None = None,
             snapshot: str | None = None,
             symbols: str | None = None) -> dict:
    """Build the recovery-IR document for ``entries`` of a loaded machine.

    ``machine_factory`` is the game adapter's ``create_machine``; when given,
    every entry is scanned with an interpreter step-length probe on a fresh
    scratch clone.  ``None`` means a static-only scan (decoder unchecked).

    ``names`` maps NE pairs to identity metadata (e.g. ``{"symbol": "_Foo",
    "module": "GAME_MODULE"}`` from a shipped symbol table); it is embedded in
    each function record and in unsupported-ledger entries alongside the
    ``ne_seg`` alias this layer adds.  ``symbols`` is the provenance
    descriptor of that symbol source (name + sha1), recorded when provided.

    Fact lists (``keep_interpreted``/``boundary_heads``/``dispatch_entries``)
    are NE pairs with dos_re's semantics.  Duplicate entries (a symbol table
    may alias one address) are scanned once.
    """
    seg_bases = machine.seg_bases

    def para(pair: NEPair) -> tuple[int, int]:
        seg, off = pair
        base = seg_bases[seg]
        if not base:
            raise ValueError(f"NE segment {seg} is not mapped")
        return base, off & 0xFFFF

    seen: set[NEPair] = set()
    ne_entries: list[NEPair] = []
    for pair in entries:
        pair = (pair[0], pair[1] & 0xFFFF)
        if pair not in seen:
            seen.add(pair)
            ne_entries.append(pair)
    para_entries = [para(p) for p in ne_entries]
    ne_of = {para(p): p for p in ne_entries}
    names = dict(names or {})

    def identity_for(cs: int, ip: int) -> dict:
        ne = ne_of[(cs, ip)]
        identity: dict[str, Any] = {"ne_seg": ne[0]}
        identity.update(names.get(ne, {}))
        return identity

    if exe is None:
        exe = (f"{machine.exe.path.name} "
               f"sha1={hashlib.sha1(machine.exe.raw).hexdigest()}")
    provenance = {
        "exe": exe,
        "snapshot": snapshot if snapshot is not None else "(loaded image)",
        "toolchain": toolchain_provenance(),
        "entries": len(para_entries),
    }
    if symbols is not None:
        provenance["symbols"] = symbols

    probe_for = None
    if machine_factory is not None:
        probe_for = lambda cs: _probe_for(machine, machine_factory, cs)  # noqa: E731

    return build_document(
        para_entries,
        fetch_for=lambda cs: _fetch_for(machine, cs),
        probe_for=probe_for,
        effect_tagger=make_effect_tagger(machine),
        provenance=provenance,
        notice=_NOTICE,
        keep_interpreted={"%04X:%04X" % para(p) for p in keep_interpreted},
        boundary_heads=frozenset(para(p) for p in boundary_heads),
        dispatch_entries=frozenset(para(p) for p in dispatch_entries),
        identity_for=identity_for,
    )
